test.Web/Controllers/ClassController.cs
using System.Web.Mvc;
using test.Models.Interfaces;
using test.Models.ViewModels;
using test.Web.Models;

namespace test.Web.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassesService _classesService;
        private readonly ITeachersService _teachersService;

        public ClassController(IClassesService classesService, ITeachersService teachersService)
        {
            _classesService = classesService;
            _teachersService = teachersService;
        }

        // GET: Class
        public ActionResult Index(long id)
        {
            var currentClass = _classesService.GetClassById(id);
            return View(new MyViewModel
            {
                Id = currentClass.Id,
                Name = currentClass.Name,
                MonitorName = currentClass.MonitorName,
                FreeTeachers = new SelectList(_teachersService.GetTeachersNotInClass(id), "Id", "FullName")
            });
        }


        public ActionResult SetMonitor(long id, long vm)
        {
            _classesService.SetMonitor(id, vm);
            return RedirectToAction("Index", new { id });
        }
    }
}

test.Web/Views/Shared/PupilEditor.cshtml
@model test.Models.ViewModels.PupilViewModel

<div class="form-group col-md-12">
    <div>
        @Html.DisplayNameFor(x => x.Name)
        @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div>
        @Html.DisplayNameFor(x => x.Surname)
        @Html.EditorFor(x => x.Surname, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(x => x.Surname)
    </div>
    <div>
        @Html.DisplayNameFor(x => x.Gender)
        @Html.EnumDropDownListFor(x => x.Gender, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(x => x.Gender)
    </div>
    @Html.HiddenFor(x => x.IdClass)
</div>
<input type="submit" value="Submit" class="btn-dark btn" />
@if (ViewBag.Title == "EditPupil")
{
    @Html.ActionLink("Cancel", "Index", "Class", new { id = Model.IdClass }, null)
}

test.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">

                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Filters", "Index", "Filters", null, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>