test.Web/Controllers/ClassController.cs
using System.Web.Mvc;
using test.Models.Interfaces;
using test.Models.ViewModels;
using test.Web.Models;

namespace test.Web.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassesService _classesService;
        private readonly ITeachersService _teachersService;

        public ClassController(IClassesService classesService, ITeachersService teachersService)
        {
            _classesService = classesService;
            _teachersService = teachersService;
        }

        // GET: Class
        public ActionResult Index(long id)
        {
            var currentClass = _classesService.GetClassById(id);
            return View(new MyViewModel
            {
                Id = currentClass.Id,
                Name = currentClass.Name,
                MonitorName = currentClass.MonitorName,
                FreeTeachers = new SelectList(_teachersService.GetTeachersNotInClass(id), "Id", "FullName")
            });
        }


        public ActionResult SetMonitor(long id, long vm)
        {
            _classesService.SetMonitor(id, vm);
            return RedirectToAction("Index", new { id });
        }
    }
}

test.Web/Controllers/PupilController.cs
using System.Web.Mvc;
using test.Models.Interfaces;
using test.Models.ViewModels;

namespace test.Web.Controllers
{
    public class PupilController : Controller
    {
        private readonly IPupilsService _pupilsService;

        public PupilController(IPupilsService pupilsService)
        {
            _pupilsService = pupilsService;
        }

        // GET: Pupil
        public ActionResult Pupils(long id)
        {
            return PartialView(_pupilsService.GetPupilsByIdClass(id));
        }

        // POST: Class/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePupil(PupilViewModel vm)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    _pupilsService.AddPupil(vm);
                }
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
            catch
            {
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
        }

        // GET: Class/Edit/5
        public ActionResult EditPupil(long id)
        {
            return View(_pupilsService.GetPupilById(id));
        }

        // POST: Class/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPupil(PupilViewModel vm)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    _pupilsService.EditPupil(vm);
                }
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
            catch
            {
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
        }

        // POST: Class/Delete/5
        [HttpPost]
        public ActionResult DeletePupil(PupilViewModel vm)
        {
            try
            {
                // TODO: Add delete logic here
                _pupilsService.DeletePupil(vm.Id);
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
            catch
            {
                return RedirectToAction("Index", "Class", new { id = vm.IdClass });
            }
        }
    }
}

test.Web/Controllers/TeacherController.cs
using System.Web.Mvc;
using test.Models.Interfaces;
using test.Models.ViewModels;
using test.Web.Models;

namespace test.Web.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeachersService _teacherService;

        public TeacherController(ITeachersService teacherService)
        {
            _teacherService = teacherService;
        }

        public ActionResult AddTeacher()
        {
            return View(new EditTeacherViewModel
            {
                TeacherTypes = new SelectList(_teacherService.GetAllTypes(), "Title", "Title")
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddTeacher(TeacherViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _teacherService.AddTeacher(vm);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult AddTeacherToClass(long? id, long? idTeacher)
        {
            if (id != null && idTeacher != null)
                _teacherService.AddTeacherToClass(id.Value, idTeacher.Value);
            return RedirectToAction("Index", "Class", new { id });
        }

        public ActionResult TeachersByClass(long id)
        {
            return PartialView("Teachers", _teacherService.GetTeachersByIdClass(id));
        }

        public ActionResult GetAllTeachers()
        {
            return PartialView("Teachers", _teacherService.GetAllTeachers());
        }

        public ActionResult RemoveTeacherFromClass(long id, long idTeacher)
        {
            _teacherService.DeleteTeacherFromClass(id, idTeacher);
            return RedirectToAction("Index", "Class", new { id });
        }

        public ActionResult ChangeDirector()
        {
            return View(new SelectList(_teacherService.GetAllTeachers(), "Id", "FullName", _teacherService.GetDirector()));
        }

        [HttpPost]
        public ActionResult ChangeDirector(long vm)
        {
            _teacherService.SetDirector(vm);
            return RedirectToAction("Index", "Home");
        }
    }
}

test.Web/Views/Class/Index.cshtml
@using test.Models.ViewModels
@model test.Web.Models.MyViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Class Details</h2>
<p>@Html.DisplayNameFor(x => x.Name)@Html.DisplayFor(x => x.Name)</p>
<p>
    @Html.DisplayNameFor(x => x.MonitorName)
    @if (!string.IsNullOrEmpty(Model.MonitorName))
    {
        @Html.DisplayFor(x => x.MonitorName)
    }
</p>
<div class="col-md-6 float-left">
@{ Html.RenderAction("Pupils", "Pupil", new {id = Model.Id}); }
    @using (Html.BeginForm("CreatePupil", "Pupil"))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("PupilEditor", new PupilViewModel {IdClass = Model.Id})
    }
</div>
<div class="col-md-6 float-right">
    @{ Html.RenderAction("TeachersByClass", "Teacher", new { id = Model.Id }); }
    @using (Html.BeginForm("AddTeacherToClass", "Teacher", new { id = Model.Id }, FormMethod.Post))
    {
        @Html.DropDownList("idTeacher", Model.FreeTeachers)
        <input type="submit" value="Add" class="btn btn-dark"/>
        @Html.ActionLink("Add new", "AddTeacher", "Teacher")
    }
</div>

test.Web/Views/Class/PupilEditor.cshtml
@model test.Models.ViewModels.PupilViewModel

<div>
    <div>
        @Html.DisplayNameFor(x => x.Name)
        @Html.EditorFor(x => x.Name)
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div>
        @Html.DisplayNameFor(x => x.Surname)
        @Html.EditorFor(x => x.Surname)
        @Html.ValidationMessageFor(x => x.Surname)
    </div>
    <div>
        @Html.DisplayNameFor(x => x.Gender)
        @Html.EnumDropDownListFor(x => x.Gender)
        @Html.ValidationMessageFor(x => x.Gender)
    </div>
</div>
<input type="submit" />